// ref: https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/end-entities-overview/certificate-statuses
export enum RevocationReason {
  KEY_COMPROMISE= "KEY_COMPROMISE",
  NOT_REVOKED= "NOT_REVOKED",
  CA_COMPROMISE= "CA_COMPROMISE",
  UNSPECIFIED= "UNSPECIFIED",
  AFFILIATION_CHANGED= "AFFILIATION_CHANGED",
  SUPERSEDED= "SUPERSEDED",
  CESSATION_OF_OPERATION= "CESSATION_OF_OPERATION",
  CERTIFICATE_HOLD= "CERTIFICATE_HOLD",
  REMOVE_FROM_CRL= "REMOVE_FROM_CRL",
  PRIVILEGES_WITHDRAWN= "PRIVILEGES_WITHDRAWN",
  AA_COMPROMISE= "AA_COMPROMISE"
}